// created by ewwink
var Clappr,YTVARS={captions:!1,languageCode:"en",qualities:[],quality:"auto"},YT=null,YoutubePlugin=Clappr.Playback.extend({name:"youtube_plugin",initialize:function(){this.settings={changeCount:0,seekEnabled:!0,left:["playpause","position","duration"],"default":["seekbar"],right:["fullscreen","volume","hd-indicator"]};YTVARS.vid=this.options.src;20<YTVARS.vid.length&&!this.options.poster?this.options.poster="https://drive.google.com/thumbnail?authuser=0&sz=w"+this.options.width+"&id="+YTVARS.vid:
this.options.poster||(this.options.poster="https://i.ytimg.com/vi/"+YTVARS.vid+"/hqdefault.jpg");Clappr.Mediator.on(Clappr.Events.PLAYER_RESIZE,this.updateSize,this);Clappr.Mediator.on(Clappr.Events.CORE_CONTAINERS_CREATED,this.render,this);this.embedYoutubeApiScript()},setupYoutubePlayer:function(){var a=this;if(YT&&YT.Player)this.embedYoutubePlayer();else this.once(Clappr.Events.PLAYBACK_READY,function(){a.embedYoutubePlayer()})},embedYoutubeApiScript:function(){YT=null;var a=this;document.getElementById("www-widgetapi-script")&&
document.getElementById("www-widgetapi-script").remove();var b=document.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("async","async");b.setAttribute("src","https://www.youtube.com/iframe_api");document.body.appendChild(b);window.onYouTubeIframeAPIReady=function(){return a.ready()}},embedYoutubePlayer:function(){var a=this,b={controls:0,disablekb:1,enablejsapi:1,iv_load_policy:3,modestbranding:1,showinfo:0,rel:0,html5:1,cc_load_policy:1,width:this.options.width,height:this.options.height};
20<YTVARS.vid.length&&(b.partnerid=30,b.docid=YTVARS.vid);"object"===typeof this.options.YoutubeVars&&$.each(this.options.YoutubeVars,function(a,d){b[a]=d});$.each(b,function(a,b){YTVARS[a]=b});YTVARS.id="yt"+this.cid;this.options.youtubePlaylist&&(b.listType="playlist",b.list=this.options.youtubePlaylist);this.player=new YT.Player("yt"+this.cid,{videoId:YTVARS.vid,playerVars:b,width:"100%",height:"100%",events:{onReady:function(){return a.ready()},onStateChange:function(b){return a.stateChange(b)},
onPlaybackQualityChange:function(b){return a.qualityChange(b)},onError:function(b,d){return a.onPlayerError(b)}}})},updateSize:function(){this.player&&this.player.setSize("100%","100%")},ready:function(){this._ready=!0;this.trigger(Clappr.Events.PLAYBACK_READY);this.player&&this.player.playVideo()},qualityChange:function(a){this.trigger(Clappr.Events.PLAYBACK_HIGHDEFINITIONUPDATE,this.isHighDefinitionInUse())},onPlayerError:function(a){this.trigger(Clappr.Events.PLAYBACK_ERROR);a=this.options.parentElement.id;
$("#"+a+" .player-poster").remove();$("#"+a+" .container").off("click");this.ended()},showError:function(){},stateChange:function(a){switch(a.data){case YT.PlayerState.PLAYING:this.enableMediaControl();a=this.getPlaybackType();this._playbackType!==a&&(this.settings.changeCount++,this._playbackType=a,this.trigger(Clappr.Events.PLAYBACK_SETTINGSUPDATE));this.trigger(Clappr.Events.PLAYBACK_BUFFERFULL);this.trigger(Clappr.Events.PLAYBACK_PLAY);YTVARS.captions&&(this.player.setOption("captions","track",
{languageCode:YTVARS.languageCode}),this.$("#youtube-plugin-cc").css({"border-bottom":"4px double #fff"}));a=this.player.getPlaybackQuality();if(YTVARS.quality!=a){console.log("###### Quality Set: "+YTVARS.quality+" - player.getPlaybackQuality: "+a);YTVARS.quality=a;for(var b=0;b<YTVARS.qualities.length;b++)if(YTVARS.qualities[b].value==a){$("#youtubeQuality").text(YTVARS.qualities[b].label);$(".youtube_plugin_control li div").removeClass("active");$('div[data-youtube-control-select="'+YTVARS.qualities[b].value+
'"]').addClass("active");break}}YTVARS.paused&&(this.enableMediaControl(),this.trigger(Clappr.Events.PLAYBACK_PAUSE),this.player.pauseVideo(),YTVARS.paused=!1);break;case YT.PlayerState.PAUSED:this.enableMediaControl();this.trigger(Clappr.Events.PLAYBACK_PAUSE);break;case YT.PlayerState.BUFFERING:this.trigger(Clappr.Events.PLAYBACK_BUFFERING);break;case YT.PlayerState.ENDED:this.options.youtubeShowRelated?this.disableMediaControl():this.trigger(Clappr.Events.PLAYBACK_ENDED)}},play:function(){var a=
this;this.player?(this._progressTimer=this._progressTimer||setInterval(function(){return a.progress()},100),this._timeupdateTimer=this._timeupdateTimer||setInterval(function(){return a.timeupdate()},100),this.player.playVideo()):this._ready?(this.trigger(Clappr.Events.PLAYBACK_BUFFERING),this._progressTimer=this._progressTimer||setInterval(function(){return a.progress()},100),this._timeupdateTimer=this._timeupdateTimer||setInterval(function(){return a.timeupdate()},100),this.setupYoutubePlayer()):
(this.trigger(Clappr.Events.PLAYBACK_BUFFERING),this.listenToOnce(this,Clappr.Events.PLAYBACK_READY,this.play))},pause:function(){clearInterval(this._timeupdateTimer);this._timeupdateTimer=null;this.player&&this.player.pauseVideo()},stop:function(){this.player&&this.player.stopVideo();this.trigger(Clappr.Events.PLAYBACK_ENDED);this.ended()},seek:function(a){this.player&&this.player.seekTo(a)},seekPercentage:function(a){if(this.player){var b=this.player.getDuration();this.seekTo(a*b/100)}},volume:function(a){this.player&&
this.player.setVolume&&this.player.setVolume(a)},progress:function(){if(this.player&&this.player.getDuration){var a=this.player.getDuration()*this.player.getVideoLoadedFraction();this.trigger(Clappr.Events.PLAYBACK_PROGRESS,{start:0,current:a,total:this.player.getDuration()})}},timeupdate:function(){this.player&&this.player.getDuration&&this.trigger(Clappr.Events.PLAYBACK_TIMEUPDATE,{current:this.player.getCurrentTime(),total:this.player.getDuration()})},isPlaying:function(){return this.player&&this.player.getPlayerState()==
YT.PlayerState.PLAYING?!0:!1},isHighDefinitionInUse:function(){return this.player&&!!this.player.getPlaybackQuality().match(/^hd\d+/)},getDuration:function(){var a=0;this.player&&(a=this.player.getDuration());return a},getPlaybackType:function(){return Clappr.Playback.VOD},disableMediaControl:function(){this.$el.css({"pointer-events":"auto"});this.trigger(Clappr.Events.PLAYBACK_MEDIACONTROL_DISABLE)},enableMediaControl:function(){this.$el.css({"pointer-events":"none"});this.trigger(Clappr.Events.PLAYBACK_MEDIACONTROL_ENABLE)},
subtitleLoaded:function(a,b){this.trigger(Clappr.Events.CONTAINER_LOADEDTEXTTRACK,a,b)},ended:function(){return!1},isReady:function(){return this._ready},render:function(){var a='<div id="yt'+this.cid+'"></div>';this.$el.attr({"data-youtube-plugin":"","class":"clappr-youtube-plugin",id:this.cid});this.$el.html(a);a=Clappr.Styler.getStyleFor([".clappr-youtube-plugin[data-youtube-plugin]{position:absolute;height:100%;width:100%;display:block;pointer-events:none"],{baseUrl:this.options.baseUrl});this.$el.append(a);
return this}});YoutubePlugin.canPlay=function(a){return!0};
var YoutubePluginControl=Clappr.UICorePlugin.extend({name:"youtube_plugin_control",bindEvents:function(){this.listenTo(this.core.mediaControl,Clappr.Events.MEDIACONTROL_CONTAINERCHANGED,this.reload);this.listenTo(this.core.mediaControl,Clappr.Events.MEDIACONTROL_RENDERED,this.render);this.listenTo(this.core.mediaControl,Clappr.Events.MEDIACONTROL_HIDE,this.hideContextMenu);this.listenTo(this.core.mediaControl,Clappr.Events.MEDIACONTROL_PLAYING,this.hideControlPaused);this.listenTo(this.core.mediaControl,
Clappr.Events.MEDIACONTROL_NOTPLAYING,this.showControlPaused);this.listenTo(this.core.mediaControl,YoutubePluginControl.MEDIACONTROL_YOUTUBECONTROL,this.updatePlaybackQuality)},unBindEvents:function(){this.stopListening(this.core.mediaControl,Clappr.Events.MEDIACONTROL_CONTAINERCHANGED);this.stopListening(this.core.mediaControl,Clappr.Events.MEDIACONTROL_RENDERED);this.stopListening(this.core.mediaControl,Clappr.Events.MEDIACONTROL_HIDE)},reload:function(){this.unBindEvents();this.bindEvents();$(document).on("click",
function(a){"youtubeQuality"!=a.target.id&&$(".youtube_plugin_control ul").hide()})},shouldRender:function(){if(!this.core.getCurrentContainer()||!this.core.getCurrentPlayback())return!1;if(YT&&YT.Player){YTVARS.qualities=[];this.ytplayer=YT.get(YTVARS.id);for(var a=this.ytplayer.getAvailableQualityLevels(),b={highres:"highres",hd1080:"1080p",hd720:"720p",large:"480p",medium:"360p",small:"240p",tiny:"144p",auto:"Auto"},c=0;c<a.length;c++)YTVARS.qualities.push({value:a[c],label:b[a[c]]});return!0}return!1},
render:function(){this.selectedQuality||(this.selectedQuality=YTVARS.quality="auto");if(this.shouldRender()){this.playbackQualities=YTVARS.qualities;var a=Clappr.template(this.template())({playbackQualities:this.playbackQualities,title:this.getTitle()});if(location.hostname!=atob("d3d3LmRva2l0di5jb20"))return;this.$el.attr({"class":this.name,"data-youtube-control-select":"",id:this.cid});this.$el.html(a);a=Clappr.Styler.getStyleFor(this.templateCSS(),{baseUrl:this.core.options.baseUrl});this.$el.append(a);
this.core.mediaControl.$(".media-control-right-panel").append(this.el);a=this.ytplayer.getOptions();-1===a.indexOf("captions")&&-1===a.indexOf("cc")&&$("#youtube-plugin-cc").css("display","none");this.updateText()}return this},onQualitySelect:function(a){this.setSelectedQuality(a.target.dataset.youtubeControlSelect);this.toggleContextMenu();a.stopPropagation();return!1},onShowMenu:function(a){this.toggleContextMenu()},toggleContextMenu:function(){this.$(".youtube_plugin_control ul").toggle()},hideContextMenu:function(){this.$(".youtube_plugin_control ul").hide()},
updatePlaybackQuality:function(a){this.setSelectedQuality(a)},setSelectedQuality:function(a){this.selectedQuality=a;var b=this.ytplayer.getCurrentTime();YTVARS.paused=2==this.ytplayer.getPlayerState()?!0:!1;this.ytplayer.stopVideo();this.ytplayer.setPlaybackQuality(a);this.ytplayer.seekTo(b,!1);this.updateText();YTVARS.quality=a},setActiveListItem:function(a){this.$("li div").removeClass("active");this.$('div[data-youtube-control-select="'+a+'"]').addClass("active")},buttonElement:function(){return this.$("#youtubeQuality")},
getTitle:function(){var a=this,b=this.selectedQuality;this.playbackQualities.forEach(function(c){c.value==a.selectedQuality&&(b=c.label)});return b},updateText:function(){this.buttonElement().text(this.getTitle());this.setActiveListItem(this.selectedQuality)},template:function(){return'<button id="youtube-plugin-cc">CC</button> <button id="youtubeQuality" data-youtube-control-button> <%= title %> </button><ul> <% for (var i = 0; i < playbackQualities.length; i++) { %> <li><div data-youtube-control-select="<%= playbackQualities[i].value %>"> <%= playbackQualities[i].label %></div></li><% }; %> </ul>'},
templateCSS:function(){return'#youtube-plugin-cc{padding:0 1px;margin-right:5px}.youtube_plugin_control[data-youtube-control-select]{float:right;margin-top:5px;position:relative}.youtube_plugin_control[data-youtube-control-select] button{background-color:transparent;color:#fff;font-family:Roboto,"Open Sans",Arial,sans-serif;-webkit-font-smoothing:antialiased;border:none;font-size:10px;cursor:pointer}.youtube_plugin_control[data-youtube-control-select] button:hover{color:#c9c9c9}.youtube_plugin_control[data-youtube-control-select] button.changing{-webkit-animation:pulse .5s infinite alternate}.youtube_plugin_control[data-youtube-control-select] > ul{display:none;list-style-type:none;position:absolute;bottom:25px;border:1px solid #000;border-radius:4px;background-color:rgba(0,0,0,0.7)}.youtube_plugin_control[data-youtube-control-select] li{position:relative;font-size:10px}.youtube_plugin_control[data-youtube-control-select] li[data-title]{padding:5px}.youtube_plugin_control[data-youtube-control-select] li div{cursor:pointer;color:#aaa;padding:2px 10px 2px 15px;display:block;text-decoration:none}.youtube_plugin_control[data-youtube-control-select] li div.active{background-color:#000;color:#fff}.youtube_plugin_control[data-youtube-control-select] li div.active:before{content:"\\2713";position:absolute;top:2px;left:4px}.youtube_plugin_control[data-youtube-control-select] li div:hover{color:#fff;text-decoration:none}@-webkit-keyframes pulse{0%{color:#fff}50%{color:#ff0101}100%{color:#B80000}}'},
hideControlPaused:function(){this.core.mediaControl.keepVisible=!1},showControlPaused:function(){this.core.mediaControl.container.isReady&&(this.core.mediaControl.keepVisible=!0)},YTShowCaptions:function(){this.ytplayer.setOption("captions","track",{languageCode:YTVARS.languageCode});this.$("#youtube-plugin-cc").css({"border-bottom":"4px double #fff"});YTVARS.captions=!0},YTHideCaptions:function(){this.$("#youtube-plugin-cc").css({"border-bottom":"none"});this.ytplayer.unloadModule("captions");YTVARS.captions=
!1},YTtoggleCaptions:function(){YTVARS.captions?this.YTHideCaptions():this.YTShowCaptions()},events:{"click [data-youtube-control-select]":"onQualitySelect","click [data-youtube-control-button]":"onShowMenu","click #youtube-plugin-cc":"YTtoggleCaptions"}});YoutubePluginControl.type="core";YoutubePluginControl.MEDIACONTROL_YOUTUBECONTROL="youtube_plugin_control";
